version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: jamstack
      POSTGRES_PASSWORD: jamstack123
      POSTGRES_DB: jamstack_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  pgdata:
